url=https://opensource-demo.orangehrmlive.com/
browser=chrome
UserName=admin
Password=admin123
DataRepositoryPath=C:\\MyWorkspace\\Selenium\\OrangeHRM-Automation\\src\\test\\resources\\DataRepository\\DataRepository.xlsx
SheetName=Login
TestGroup=sanity